### ISSUE TITLE
invalid address

### ISSUE THREAD

**Issue by Abdo-Gue** [6eer/uniswap-sushiswap-arbitrage-bot#1]
Hey, 
Thanks for sharing this awesome project!
I've tried to follow along with the instructions, but after configuring the env file, and minting the demo tokens, I wasn't able to run the bot_flashswap.js file. 
I get the following error: 

`  reason: 'invalid address (argument="address", value=undefined, code=INVALID_ARGUMENT, version=address/5.1.0)',
  code: 'INVALID_ARGUMENT',
  argument: 'tokenA',
  value: undefined`
  
  Any idea how I can solve this?

**Comment by 6eer** [comment]
Yeah sure, but I need some context, with this I can't do much. 
There are many steps until run the bots and I dont know if its a bug or you made a mistake along the way. 
At lest I would need the steps you do, maybe the .env file and, just for in case, your OS.

**Comment by The-WiZaX** [comment]
Hey Abdo-Gue, 6eer, sorry for hijacking the thread

6eer, do you have a telegram or somewhere to reach you? I don't see any contact information, i'd like to discuss
