### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by breakingbad8** [6eer/uniswap-sushiswap-arbitrage-bot#3]
Hi Love your project . Do you have any contact like telegram , Skype can easy to get in touch . 

I do have a interesting short term job need you help .

**Comment by 6eer** [comment]
Hi, I'm glad to hear that.
Yeah! but email me to falcho04@hotmail.com first!

Greetings

**Comment by breakingbad8** [comment]
Hi How are You Bro  , we would like to build a (uniswap & sushi ) arbitrage
bot . I know you have full experience on this field .
- shortest path ( classic graph search , bellman-ford ) to get the
opportunity of arbitrage (or other better idea )
- how to compete with other arbitrage bot
- Ethereum block interval is 15 seconds, you have to do 3 things in 15
seconds:
Update the reserves of each trading pair:
Small amount of trading pairs: batch request for the states of all trading
pairs
Large amount of trading pairs: batch request, then parse every new block,
if there is a event in (Swap, Sync, Mint, Burn), update the related pair
reserves.
Find the best path and optimal input amount:
Optimize DFS, explore other algorithms like bellman-ford, spfa, etc.
Send the transaction:
Call UniswapV2Router02.getAmountsOut before you send your tx, confirm that
we can really make a profit.

Bro let me know you are willing take the job 😊
