### ISSUE TITLE
Ganache cli fork not update getReserves() inside 'data' suscribeBlock . How to test?

### ISSUE THREAD

**Issue by alvarheras** [6eer/uniswap-sushiswap-arbitrage-bot#4]
Hello

Look at your project is fine. But I see something when you debug your project. How can you debug it?

I understand that the method of subscribe ('newBlockHeaders'); you won't be able to get the data with the ganache-cli fork.

You will always receive the same block so the prices obtained within that event will be the same unless the ganache service is restarted.

Is there any way to debug this subscribe with some ropsten or fork network provider on mainnet with galache?

Greetings

**Comment by 6eer** [comment]
If u only wanna debug the code inside the subscribe method, u can initiate ganache-cli with the '-b' option or simply without it and send transaction manually, ganache will append this new transaction in a new block, so, the event will fire. 

Bellow part of the [README.md](https://github.com/trufflesuite/ganache-cli/blob/master/README.md#options) of ganache-cli:

-b or --blockTime: Specify blockTime in seconds for automatic mining. If you don't specify this flag, ganache will instantly mine a new block for every transaction. Using the --blockTime flag is discouraged unless you have tests which require a specific mining interval.

In the demo I use the -b option (automining) to fire the 'newBlockHeaders' event.

**Comment by alvarheras** [comment]
With the option of the fork to ganache-cli

When I do not indicate or indicate the -b option the blocks change but the price obtained through the Factory is the same unless I deploy my contracts again.

![vfvfvfvfvfvffvfvfvf](https://user-images.githubusercontent.com/11508953/122762355-86e84700-d29d-11eb-9a10-006c63b87b43.PNG)

My code: 

```
const uFactory = new web3.eth.Contract(factoryUniV2.abi,addrUFactory); /
uPair0 = new web3.eth.Contract(pairUniV2.abi, (await uFactory.methods.getPair(addrEth, addrDai).call()) )
               // --> inside event 'data'
		let uReserves;
		uReserves = await uPair0.methods.getReserves().call();
		// console.log(uReserves);
	 	uReserve0 = uReserves[0]; //dai
	    uReserve1 = uReserves[1]; //eth
	    console.log("Reserva 1 (ether) --->" + uReserve1);
	    console.log("Reserva 2 (dai) --->" + uReserve0);
	    priceEth = (uReserve0/uReserve1); //dai per eth
	    console.log("Dai por Eth ---> " + priceEth); // eth price in route uniswap 2
```

Any ideas how to change this to get the updated price?

Greetings, thank you very much

**Comment by 6eer** [comment]
but why the prices should change? you are forking locally, so the only transaction that your fork can see its your transactions, so the only way to change the prices are u withdrawing funds manually from the pools. I say withdraw because i don't remember if Uniswap allows u to provides funds that disrupt the ratio (price). And keep in mind that there is an option that allows u save the changes that u mad to the chain (the deploys & trnasactions u made)

--db: Specify a path to a directory to save the chain database. If a database already exists, ganache-cli will initialize that chain instead of creating a new one.

**Comment by alvarheras** [comment]
You're right,

With the fork to mainner with ganache I thought you could test this part reading from mainner.

```
suscribeBlock.on('data', async function(blockHeader) {
	
	console.log(blockHeader);
	// logic inside try and catch --> 
	try {
	} 
    catch(error) {
        console.log(error)
    }

});
```
I am looking for is to implement the Uniswap functions of flash Swap, but through ropsten they did not work for me. Do you know if on a fork with ganache I can correctly test my token swap functions with uniswap?

Greetings thank you
